@Test(expected=<YourExpectedException>.class)
public void testExceptionThrown() {
// call the method that throws exception
    }