<p>This exception is thrown when an application attempts to perform a networking operation on its main thread. Run your code in <a href=""http://developer.android.com/reference/android/os/AsyncTask.html""><code>AsyncTask</code></a>:</p>

<pre><code>class RetrieveFeedTask extends AsyncTask&lt;String, Void, RSSFeed&gt; {

    private Exception exception;

    protected RSSFeed doInBackground(String... urls) {
        try {
            URL url= new URL(urls[0]);
            SAXParserFactory factory =SAXParserFactory.newInstance();
            SAXParser parser=factory.newSAXParser();
            XMLReader xmlreader=parser.getXMLReader();
            RssHandler theRSSHandler=new RssHandler();
            xmlreader.setContentHandler(theRSSHandler);
            InputSource is=new InputSource(url.openStream());
            xmlreader.parse(is);
            return theRSSHandler.getFeed();
        } catch (Exception e) {
            this.exception = e;
            return null;
        }
    }

    protected void onPostExecute(RSSFeed feed) {
        // TODO: check this.exception 
        // TODO: do something with the feed
    }
}
</code></pre>

<p>How to execute the task:</p>

<pre><code>new RetrieveFeedTask().execute(urlToRssFeed);
</code></pre>

<p>Don't forget to add this to <code>AndroidManifest.xml</code> file:</p>

<pre><code>&lt;uses-permission android:name=""android.permission.INTERNET""/&gt;
</code></pre>
